.color1 { #a7c5bd };
.color2 { #e5ddcb };
.color3 { #eb7b59 };
.color4 { #cf4647 };
.color5 { #524656 };

<h1 style= "color:#cf4647; text-align: center"> Caso de Estudio Banco UNO </h1>

<center> <img src= "banco.jpeg" style= "width:1100px; height:300px" </center>
<h3 style= "color:#a7c5bd"> Problema de Negocio</h3>
<p> 
Actualmente, la institución enfrenta los siguientes desafíos:

Aumento en la morosidad: La tasa de incumplimiento de pago ha aumentado en los últimos años, impactando la rentabilidad del banco.
Decisiones basadas en criterios rígidos: El análisis crediticio se basa en reglas fijas que no consideran la variabilidad de cada cliente.
Demoras en el proceso de evaluación: La evaluación manual de cada solicitud toma tiempo y genera retrasos en la asignación de créditos.
La alta dirección del banco busca una solución basada en ciencia de datos para mejorar la toma de decisiones y reducir el riesgo crediticio.

Objetivo del Proyecto de Ciencia de Datos

El objetivo de este proyecto es desarrollar un modelo de Machine Learning que pueda predecir si un cliente incumplirá su pago el siguiente mes.

Las preguntas clave que el modelo debe responder son:

✅ ¿Cuáles son los factores más determinantes en la probabilidad de incumplimiento?</br>
✅ ¿Se puede predecir si un cliente incumplirá su pago el próximo mes?</br>
✅ ¿Cómo mejorar la precisión y eficiencia del proceso de evaluación crediticia?</br>

Para ello, se analizará un conjunto de datos que contiene información histórica de clientes, incluyendo su comportamiento de pago, límites de crédito, estado financiero y características personales.</p>

In [8]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

from ydata_profiling import ProfileReport

In [9]:
dfCredito =pd.read_excel("ETL_credit.xlsx")
dfCredito.shape

(2395, 25)

In [3]:
dfCredito.head(4)

,Unnamed: 0,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month (Y)
0,0,120000,female,university,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,default
1,1,90000,female,university,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,not default
2,2,50000,female,university,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,not default
3,3,50000,male,university,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,not default

In [4]:
dfCredito= dfCredito.drop (columns=["Unnamed: 0"])
dfCredito.head(4)

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month (Y)
0,120000,female,university,2,26,-1,2,0,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,default
1,90000,female,university,2,34,0,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,not default
2,50000,female,university,1,37,0,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,not default
3,50000,male,university,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,not default

In [10]:
profile = ProfileReport(dfCredito, title ="EDA_Creditos")
profile.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/25 [00:00<?, ?it/s]
 16%|█▌        | 4/25 [00:00<00:00, 37.16it/s]
 32%|███▏      | 8/25 [00:00<00:00, 32.63it/s]
 52%|█████▏    | 13/25 [00:00<00:00, 36.24it/s]
 68%|██████▊   | 17/25 [00:00<00:00, 36.00it/s]
100%|██████████| 25/25 [00:00<00:00, 38.74it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

KeyboardInterrupt:

In [ ]:
print(dfCredito.columns)

In [ ]:
dfCredito['BILL_AMT1'].replace(0,1,inplace=True)

dfCredito['BILL_AMT2'].replace(0,1,inplace=True)

dfCredito['BILL_AMT3'].replace(0,1,inplace=True)

dfCredito['BILL_AMT4'].replace(0,1,inplace=True)

dfCredito['BILL_AMT5'].replace(0,1,inplace=True)

dfCredito['BILL_AMT6'].replace(0,1,inplace=True)

dfCredito['PAY_0'].replace(-2,-1,inplace=True)

dfCredito['PAY_2'].replace(-2,-1,inplace=True)

dfCredito['PAY_3'].replace(-2,-1,inplace=True)

dfCredito['PAY_4'].replace(-2,-1,inplace=True)

dfCredito['PAY_5'].replace(-2,-1,inplace=True)

dfCredito['PAY_6'].replace(-2,-1,inplace=True)

dfCredito['PAY_0'].replace(0,-1,inplace=True)

dfCredito['PAY_2'].replace(0,-1,inplace=True)

dfCredito['PAY_3'].replace(0,-1,inplace=True)

dfCredito['PAY_4'].replace(0,-1,inplace=True)

dfCredito['PAY_5'].replace(0,-1,inplace=True)

dfCredito['PAY_6'].replace(0,-1,inplace=True)

print ("Datos ajustados")

In [7]:
dfCredito =pd.read_excel("ETL_credit.xlsx")